port: $PORT

tls {
  cert_file: "/tmp/certs/nats-server.pem"
  key_file: "/tmp/certs/nats-server.key"
  ca_file: "/tmp/certs/rootCA.pem"
  verify: true
}

authorization {
  user: $NATS_USERNAME
  password: $NATS_PASSWORD
}

jetstream {
  store_dir: "/data/jetstream"
}